"""
flow_aggregator.py
===================
CICIDS2017's features were generated by CICFlowMeter, a tool that groups raw
packets into bidirectional "flows" (5-tuple: src IP, dst IP, src port, dst
port, protocol) and computes ~78 statistical features per flow (duration,
packet-length stats, inter-arrival times, flag counts, etc).

Scapy only gives us raw packets, not flow features — so for live capture to
feed the model trained on CICIDS2017, we need to do the same aggregation
ourselves. This module is a deliberately simplified re-implementation: it
computes the subset of features that matter most (and that showed up with
high importance in training — check artifacts/feature_importance.png) and
zero-fills whatever the trained model expects but this aggregator doesn't
produce. That alignment happens in detection/ml_detector.py.

For your report: this is a known, worth-discussing limitation of live IDS
systems trained on offline flow-exporter datasets — it's a legitimate point
to raise in your viva, not something to hide.
"""

import time
from collections import defaultdict

import config


class _FlowState:
    __slots__ = (
        "start_time", "last_time", "fwd_lengths", "bwd_lengths",
        "fwd_count", "bwd_count", "syn_count", "ack_count", "fin_count",
        "rst_count", "psh_count", "urg_count", "src_ip", "dst_ip",
        "src_port", "dst_port", "protocol",
    )

    def __init__(self, src_ip, dst_ip, src_port, dst_port, protocol, now):
        self.start_time = now
        self.last_time = now
        self.fwd_lengths = []
        self.bwd_lengths = []
        self.fwd_count = 0
        self.bwd_count = 0
        self.syn_count = 0
        self.ack_count = 0
        self.fin_count = 0
        self.rst_count = 0
        self.psh_count = 0
        self.urg_count = 0
        self.src_ip = src_ip
        self.dst_ip = dst_ip
        self.src_port = src_port
        self.dst_port = dst_port
        self.protocol = protocol


class FlowAggregator:
    """
    Call add_packet() for every sniffed packet. Call flush_expired() on a
    timer (e.g. every FLOW_WINDOW_SECONDS) to pop completed flows out as
    feature dicts ready for the ML detector.
    """

    def __init__(self, window_seconds: float = None):
        self.window_seconds = window_seconds or config.FLOW_WINDOW_SECONDS
        self._flows: dict[tuple, _FlowState] = {}

    @staticmethod
    def _flow_key(src_ip, dst_ip, src_port, dst_port, protocol):
        # Canonicalize direction so both sides of a conversation map to one flow
        if (src_ip, src_port) <= (dst_ip, dst_port):
            return (src_ip, dst_ip, src_port, dst_port, protocol)
        return (dst_ip, src_ip, dst_port, src_port, protocol)

    def add_packet(self, pkt_meta: dict):
        now = pkt_meta["timestamp"]
        key = self._flow_key(
            pkt_meta["src_ip"], pkt_meta["dst_ip"],
            pkt_meta.get("src_port"), pkt_meta.get("dst_port"),
            pkt_meta.get("protocol"),
        )
        flow = self._flows.get(key)
        if flow is None:
            flow = _FlowState(
                pkt_meta["src_ip"], pkt_meta["dst_ip"],
                pkt_meta.get("src_port"), pkt_meta.get("dst_port"),
                pkt_meta.get("protocol"), now,
            )
            self._flows[key] = flow

        is_forward = pkt_meta["src_ip"] == flow.src_ip
        length = pkt_meta.get("length", 0)
        if is_forward:
            flow.fwd_lengths.append(length)
            flow.fwd_count += 1
        else:
            flow.bwd_lengths.append(length)
            flow.bwd_count += 1

        flags = pkt_meta.get("flags", set())
        if "S" in flags:
            flow.syn_count += 1
        if "A" in flags:
            flow.ack_count += 1
        if "F" in flags:
            flow.fin_count += 1
        if "R" in flags:
            flow.rst_count += 1
        if "P" in flags:
            flow.psh_count += 1
        if "U" in flags:
            flow.urg_count += 1

        flow.last_time = now

    def flush_expired(self) -> list[dict]:
        """Pop flows that have been idle longer than window_seconds and
        return their computed feature dicts."""
        now = time.time()
        expired_keys = [
            k for k, f in self._flows.items()
            if now - f.last_time >= self.window_seconds
        ]
        results = []
        for k in expired_keys:
            flow = self._flows.pop(k)
            results.append(self._compute_features(flow))
        return results

    def flush_all(self) -> list[dict]:
        """Force-flush every active flow (used at shutdown / batch end)."""
        results = [self._compute_features(f) for f in self._flows.values()]
        self._flows.clear()
        return results

    @staticmethod
    def _stats(values):
        if not values:
            return {"max": 0, "min": 0, "mean": 0, "std": 0, "total": 0}
        n = len(values)
        mean = sum(values) / n
        var = sum((v - mean) ** 2 for v in values) / n
        return {
            "max": max(values), "min": min(values),
            "mean": mean, "std": var ** 0.5, "total": sum(values),
        }

    def _compute_features(self, flow: _FlowState) -> dict:
        duration = max(flow.last_time - flow.start_time, 1e-6)
        fwd_stats = self._stats(flow.fwd_lengths)
        bwd_stats = self._stats(flow.bwd_lengths)
        total_packets = flow.fwd_count + flow.bwd_count
        total_bytes = fwd_stats["total"] + bwd_stats["total"]

        # Keys are named to match CICIDS2017 columns wherever practical, so
        # detection/ml_detector.py can line them up against feature_columns.json
        return {
            "_meta": {
                "src_ip": flow.src_ip, "dst_ip": flow.dst_ip,
                "src_port": flow.src_port, "dst_port": flow.dst_port,
                "protocol": flow.protocol,
            },
            "Flow Duration": duration * 1_000_000,  # CICIDS2017 uses microseconds
            "Total Fwd Packets": flow.fwd_count,
            "Total Backward Packets": flow.bwd_count,
            "Total Length of Fwd Packets": fwd_stats["total"],
            "Total Length of Bwd Packets": bwd_stats["total"],
            "Fwd Packet Length Max": fwd_stats["max"],
            "Fwd Packet Length Min": fwd_stats["min"],
            "Fwd Packet Length Mean": fwd_stats["mean"],
            "Fwd Packet Length Std": fwd_stats["std"],
            "Bwd Packet Length Max": bwd_stats["max"],
            "Bwd Packet Length Min": bwd_stats["min"],
            "Bwd Packet Length Mean": bwd_stats["mean"],
            "Bwd Packet Length Std": bwd_stats["std"],
            "Flow Bytes/s": total_bytes / duration,
            "Flow Packets/s": total_packets / duration,
            "SYN Flag Count": flow.syn_count,
            "ACK Flag Count": flow.ack_count,
            "FIN Flag Count": flow.fin_count,
            "RST Flag Count": flow.rst_count,
            "PSH Flag Count": flow.psh_count,
            "URG Flag Count": flow.urg_count,
        }
